# Regresión lineal múltiple - Salsberry Realty
1. Determinar las variables independientes
2. Determinar la variable dependiente
3. Obtener el valor de intersección
4. Estimar el corto de calefacción para una Temperatura externa media de 30°, 5 pulgadas de aislamiento y un calentador con antigüedad de 10 años.

In [6]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

In [2]:
#importar datos
df = pd.read_csv('SalsberryRealty.csv')
df.head()

   Cost  Temp  Insul  Age  Garage
0   250    35      3    6       0
1   360    29      4   10       1
2   165    36      7    3       0
3    43    60      6    9       0
4    92    65      5    6       0

# 1. Determinar las variables independientes
x1, x2, x3

In [10]:
X = df[['Temp', 'Insul', 'Age']]
df[['Temp', 'Insul', 'Age']]

    Temp  Insul  Age
0     35      3    6
1     29      4   10
2     36      7    3
3     60      6    9
4     65      5    6
5     30      5    5
6     10      6    7
7      7     10   10
8     21      9   11
9     55      2    5
10    54     12    4
11    48      5    1
12    20      5   15
13    39      4    7
14    60      8    6
15    20      5    8
16    58      7    3
17    40      8   11
18    27      9    8
19    30      7    5

# 2. Determinar variable dependiente

In [12]:
Y = df[['Cost']]
df[['Cost']]

    Cost
0    250
1    360
2    165
3     43
4     92
5    200
6    355
7    290
8    230
9    120
10    73
11   205
12   400
13   320
14    72
15   272
16    94
17   190
18   235
19   139

In [16]:
#Ajustar el modelo de regresión múltiple
model = LinearRegression() 
model.fit(X, Y) #Entrenando el modelo 
y_pred = model.predict(X)
#y_pred

In [18]:
#Metricas estadísticas
mse = mean_squared_error(Y, y_pred) #Error de la media cuadrática
r2 = r2_score(Y, y_pred) #varianza

# 3. Valor de intersección

In [19]:
model.intercept_

array([427.19380332])

In [21]:
#coeficientes
print('Coeficientes: ', model.coef_)
print('Error cuadrático medio', mse)
print('Varianza: ', r2)

Coeficientes:  [[ -4.58266263 -14.83086269   6.10103206]]
Error cuadrático medio 2084.7638583181542
Varianza:  0.8041700664870349

# 4. Estimar para 30°, aislamiento de 5", antigüedad de 10 años.

In [25]:
Y = model.predict([[30, 5, 10]])
print("El costo de calefacción estimado es: ", Y)

El costo de calefacción estimado es:  [[276.56993172]]

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(